### ISSUE TITLE
LCFS - Pills in AG Grid display tables

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#1249]
**Describe the task**
Expand the columns at the end of the Allocation Agreement and Export AG grids to ensure all content is fully visible and not truncated. This change should provide adequate space for data entries and improve readability within the tables.

**Purpose**
To enhance the usability and clarity of the input AG grids by ensuring that columns at the end of the table are sufficiently wide to display all content without truncation.

**Acceptance Criteria**

- [ ] Expand the column widths at the end of the Allocation Agreement AG grid to fully display content without truncation.
- [ ]  Expand the column widths at the end of the Export AG grid to fully display content without truncation.
- [ ]  Ensure that the expanded columns accommodate long text, numerical values, and dropdown options where applicable.
- [ ]  Test the updated grid layout to confirm that it improves readability without impacting usability or functionality.
- [ ]  Validate the changes across different screen resolutions and devices to ensure consistency.
- [ ] If all pills aren't displayed put a "+# " to indicate the number of pills that are not appearing e.g. +2

**Additional context**

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the column definitions and grid options to ensure all content is fully visible and not truncated in the Allocation Agreement table. Adjusted the autoSizeStrategy and added a specific minWidth for certain columns.

You can review changes in this commit: https://github.com/lattaai13/bcgov-lcfs-1249/commit/3711ab12f10f1b37806bd9e706d501e73619280c.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
