### ISSUE TITLE
LCFS - Save draft of new transaction

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#349]
**Description:**
Develop the functionality to save a draft of a new transaction:

- Save Draft button
- Requires the three transaction inputs (transaction type, select organization, compliance units) to not be blank / be filled out / selected
- If effective date is not entered, effective date defaults to the date of director approval (this functionality will be handled in the director approval card)
- Clicking the 'Save' button creates the transaction and sets the status to 'Draft'. 
- Creating the transaction assigns an ID number to the transaction (i.e., a transaction ID number, similar to TFRS functionality where every transaction is given a unique ID number, sequential order).
- Replaces 'New transaction' title on page to chosen transaction type and assigned ID number (see wireframes below)
- A success alert appears ([Material UI examples](https://mui.com/material-ui/react-alert))
- A transaction history record is saved to the database and visible in the UI when viewing the transaction: Saved on [Month DD, YYYY] by [User] of [Organization]. This record is based on the IDIR user with the government analyst role that clicked the 'Save' button.
- The created transaction is only visible to IDIR users; it is not visible to the external organization that the transaction relates
- The user remains on the transaction page with fields still editable.
- The comment free text field (director comments to the organization) is saved to the database, if there is a comment added (see card #346 for development of this feature).
- Grey text box with explanation of effective date persists.

**Validation Messaging:**
May be dependent on front-end vs. back-end validation: 
- Has not selected a transaction type: "Select a transaction type"
- Has not selected an organization from the drop-down menu: "Select an organization"
- Has not inputted a value into the compliance units field: "Compliance units cannot be blank"
- Has inputted a negative value into the compliance units field while also selecting the initiative agreement transaction type: "Compliance units for initiative agreements cannot be negative"

**Balance Validation:**
For an 'administrative adjustment' transaction type, a negative transaction cannot be more than the organization's compliance balance (i.e., their balance minus any units in reserve). In other words, a negative administrative adjustment transaction cannot put an organization into a negative compliance balance situation. We want the system to validate the transaction to ensure that this doesn't happen, and to throw an error when the analyst goes to save a draft of the transaction or recommends to the director (recommending validation handled in #351 )
- Validation messaging: "Error! The Transaction will cause the organization's compliance balance to be negative." 

**Wireframe:**
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165300444/simulate/sitemap

**Purpose and benefit to user:**
Allows the IDIR government analyst user to save a draft of the transaction to be processed later and/or by a different user

**Acceptance Criteria:**

- [x] Given I am a IDIR user, When I am clicking on save draft button, then the transaction should be saved in the database and a new transaction ID and saved details should be updated.
- [x] Given I am a BCeID user, I shouldn't be able to perform a new transaction.

**Development Checklist:**
- [x] Create a ‘Save Draft’ button and add it to the new transaction page.
- [ ] Configure the ‘Save Draft’ button to only be enabled if the three transaction inputs (transaction type, select organization, compliance units) are not blank.
- [x] Implement logic to default the effective date to the date of director approval if it is not entered.
- [x] Implement logic to create the transaction and set the status to ‘Draft’ when the ‘Save Draft’ button is clicked and show success alert without redirecting to a different page. Ensure to update the related fields as well.
- [x] Configure the ‘New transaction’ title on the page to be replaced with the chosen transaction type and assigned ID number.
- [x] Implement logic to display a success alert
- [x] Implement logic to save a transaction history record to the database and make it visible in the UI when viewing the transaction. The record should indicate that the transaction was saved on [Month DD, YYYY] by [User] of [Organization]. This record should be based on the IDIR user with the government analyst role that clicked the ‘Save’ button.
- [x] Implement logic to ensure that the created transaction is only visible to IDIR users and not to the external organization that the transaction relates to.
Ensure that the user remains on the transaction page with fields still editable after clicking the ‘Save Draft’ button.
- [x] Implement logic to save the comment free text field (director comments to the organization) to the database if there is a comment added.
- [x] Ensure that the grey text box with an explanation of the effective date persists.
- [x] Implement validation messaging to be displayed if the user has not selected a transaction type, an organization from the drop-down menu, or has not inputted a value into the compliance units field. If the user has inputted a negative value into the c, appropriate validation messaging should also be displayed.

**Notes:**

**Comment by justin-lepitzki** [comment]
@Grulin Looks good. A few additions/tweaks I made: 

1.  as you correctly pointed out, we needed some information about data validation messaging. Here we are trying to capture what happens when you don't fill out a required field or input an incorrect value (e.g., negative compliance unit value for initiative agreement transaction type). We need to give the developers the specific language to use; plain language is best and we should be consistent in how we communicate these types of errors / issues. As always, Al and Kailee can help us with this type of messaging if needed. 

2. I expanded the bullet below to clarify that the assigning of an effective date when the field is left blank will be handled in a different card. Due to the business logic here, we won't know this date until the director clicks on the approve button; thus, it makes sense to incorporate that functionality within the director approval card. 

- If effective date is not entered, effective date defaults to the date of director approval (this functionality will be handled in the director approval card)

3. I changed the bullet below to say that the created transaction is only visible to IDIR users. This includes the transaction history record, but we want hide the entire transaction from external organizations until it has been approved; at that time, it will become visible to the organization involved in the transaction.

- The transaction history record is only visible to IDIR users

4. Careful with copy/pasting from previous cards. You referenced transfers in the **Purpose and benefit to user:** section when it should reference transaction: Allows the IDIR government analyst user to save a draft of the **transaction** to be processed later and/or by a different user

**Comment by Grulin** [comment]
**Note to run this past the devs**
Do we want to prefix the transaction types for filtering id#? Because transfer, admin adjustments and IA transactions are in separate tables, there is the potential for them to have the same numerical id#. We could differentiate between the transaction types in the id by prefixing them with AA#,IA# and CUT#.

**Comment by airinggov** [comment]
recived this error trying to save a negative value as admin adjustment



![Image](https://github.com/bcgov/lcfs/assets/20462387/dbe2e324-7124-49bd-a696-ae87a5e32c7e)

**Comment by AlexZorkin** [comment]
This issue will be fixed once ticket #382 is merged.
