### ISSUE TITLE
LCFS - Recommend transaction

### ISSUE THREAD

**Issue by Grulin** [bcgov/lcfs#351]
**Description:**
Develop the functionality to recommend a new transaction or draft transaction:

- 'Recommend' button in the bottom right hand corner of the transaction page
- Only available to IDIR users with the government analysts role.
- Requires the three transaction inputs (transaction type, select organization, compliance units) to not be blank / be filled out / selected (see validation section below for more info)
- If effective date is not entered, effective date defaults to the date of director approval (this functionality will be handled in the director approval card).
- Clicking on the 'Recommend' button brings up a confirmation modal window that says, "Are you sure you want to recommend approval of this transaction?" and contains two buttons: Recommend & Cancel
- Clicking the Cancel button in the modal window brings the user back to the transaction screen
- Clicking on the 'Recommend' button in the modal window (1) brings up a success message/alert/modal, (2) The user is returned to the transaction page, (3) The transaction row for the transaction is highlighted, and (4) the transaction status is changed to Recommended.
- If the transaction has not been created yet (i.e., not saved as a draft before clicking on the Recommend button) then recommending the transaction assigns an ID number to the transaction (i.e., a transaction ID number, similar to TFRS functionality where every transaction is given a unique ID number, sequential order). Note: if the user has already saved a draft of the transaction (status = draft) then a transaction ID will already be assigned.
- The comment free text field (director comments to the organization) is saved to the database, if there is a comment added (see card #346 for development of this feature).
- A transaction history record is saved to the database and visible in the UI when viewing the transaction: Recommended on [Month DD, YYYY] by [User] of [Organization]. This record is based on the IDIR user with the Government Analyst role that clicked the Recommend button.
- The transaction continues to be visible to only IDIR users; it is still not visible to the external organization that the transaction relates

**Validation Messaging:**
May be dependent on front-end vs. back-end validation: 
- Has not selected a transaction type: "Select a transaction type"
- Has not selected an organization from the drop-down menu: "Select an organization"
- Has not inputted a value into the compliance units field: "Compliance units cannot be blank"
- Has inputted a negative value into the compliance units field while also selecting the initiative agreement transaction type: "Compliance units for initiative agreements cannot be negative"

**Balance Validation:**
For an 'administrative adjustment' transaction type, a negative transaction cannot be more than the organization's compliance balance (i.e., their balance minus any units in reserve). In other words, a negative administrative adjustment transaction cannot put an organization into a negative compliance balance situation. We want the system to validate the transaction to ensure that this doesn't happen, and to throw an error when the analyst goes to save a draft of the transaction or recommends to the director (recommending validation handled in #351 )
- Validation messaging: "Error! The Transaction will cause the organization's compliance balance to be negative."

**Wireframe:**
https://preview.uxpin.com/59145260c7d8cc48969ac79401cc03d84843c3d9#/pages/165300924/simulate/sitemap

**Purpose and benefit to user:**
Provides the necessary functionality for government users to make transaction recommendations to the director.

**Acceptance Criteria:**

- [x] Given I am an analyst , When I am on the transactions page, then the 'recommend' button ui should be shown
- [x] Given I am an analyst , When I am on the recommend button is clicked, then a confirmation modal should be shown
- [x] Given I am an analyst , When I am on the modal, then clicking on the 'recommend' button will show a success message and the user is returned to the transaction page.
- [x] Given I am an analyst , When I am on the transaction page after recommending, the row for the created recommended transaction should be highlighted and the status should be changed to 'recommended'

**Development Checklist:**
- [ ] Create a confirmation modal
- [ ] create a success modal/toast
- [ ] create the backend service methods and database query to save the information

**Comment by justin-lepitzki** [comment]
@Grulin I had to rework the contents of this card a bit. There were some missing components and complexities that needed to be covered. For missing components, we needed to add a confirmation modal window, transaction history record, and information about navigation after the recommendation is made. The latter differs from saving a draft in that the system takes the user back to the transaction page (among other things, see bullets in the description). In terms of complexities, there are two potential pathways for recommending a transaction; the first is when a draft has already been saved, and the second is when the user has not saved the transaction as a draft (goes straight to recommendation). In the latter scenario, the transaction is created (assigned an ID; stored in the database) when the user clicks the Recommend button (in the former draft saved scenario, the transaction has already been created). Therefore, we needed some of the same info from the save draft card about creating a transaction ID and saving to the database. We also needed the same data validation / restrictions checks on the Recommend button as we have on the Save Draft button (e.g., fields can't be blank, must be selected, etc.) because the user may go straight to the recommend option (no saved draft) or they may edit the information after the draft is saved but prior to recommendation. 

Most of the information I included or changed came from #256 and #349

**Comment by Grulin** [comment]
After an IDIR analyst recommends a transaction, they should be returned to the "Transactions" page and the transaction they just recommended should be highlighted.

**Comment by AlexZorkin** [comment]
added this logic.

**Comment by Grulin** [comment]
Thanks @AlexZorkin. This works now, but the modal window is showing the following:


![Image](https://github.com/bcgov/lcfs/assets/156380046/0be82a62-e755-4ecf-b256-738c28656e91)

It should say "Are you sure you want to recommend approval of this transaction?"
