### ISSUE TITLE
LCFS - revised transfer details not saving when editing a draft transfer and then signing and sending

### ISSUE THREAD

**Issue by justin-lepitzki** [bcgov/lcfs#494]
**Describe the Bug**
When editing a saved draft transfer, changes to the transfer details are not being saved when signing and sending. Instead, the system is reverting back to the previously saved details. 

**Expected Behaviour**
The system should be (re)saving the transfer details to the database when a user edits a draft transfer and then immediately signs & sends it. 

**Actual Behaviour**
The system is not saving the changed transfer details and instead is reverting back to the previously saved values. 

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: BCeID user, transfer & signing authority roles
1. Go to a draft transfer 
2. Edit details of the transfer (e.g., quantity of units, price per unit, etc.)
3. Click on the Sign and Send button

**Comment by justin-lepitzki** [comment]
May be fixed already in Kevin's PR

**Comment by Grulin** [comment]
The issue I see for this one is that you can edit and save a draft transfer successfully, but when you return to the Transactions table and select the transfer again, what is prepopulated in the most recent version is the previous version still. And hitting sign and send from here will submit this previous version, even though you had previously changed it and saved it. 

For example, if I open a draft transfer and change the # of compliance units from 2 to 20, save, and then return to the transactions table, when I reopen the transfer for a second time, the # of compliance units still shows 2 instead of the 20 that I just saved. 

Screenshot shows the following error in this example:


![Image](https://github.com/bcgov/lcfs/assets/156380046/03573f7f-a6a0-401f-93ba-cb2b6a76ca78)

**Comment by Grulin** [comment]
![Image](https://github.com/bcgov/lcfs/assets/156380046/ebe84a4c-b414-4847-91a0-210ee3063834)

**Comment by justin-lepitzki** [comment]
There appears to be two issues here that seem closely related. Completion of this card should fully investigate and resolve both the issue described in the main body of the card and the issue discovered by Lindsy.
